version: '2'
services:
  zookeeper1:
    image: bitnami/zookeeper:latest
    hostname: zookeeper1
    ports:
      - '2181:2181'
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    volumes:
      - zookeeper1-data:/bitnami/zookeeper
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - '9092:9092'
    links:
      - zookeeper1
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: 'topic-test:1:1'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    ports:
      - '8080:8080'
    environment:
      KAFKA_BROKERS: 'kafka:9092'
    depends_on:
      - kafka
volumes:
  zookeeper1-data:
